spring.application.name=learn-spring-boot

spring.profiles.active=default
#spring.profiles.active=dev

logging.level.org.springframework=debug

currency-service.url=http://default.in28minutes.com
currency-service.user-name=defaultUserName
currency-service.key=defaultKey

#spring-boot-actuator
management.endpoints.web.exposure.include=*