spring.application.name=restful-web-services
logging.level.org.springframework=debug
management.endpoints.web.exposure.include=*
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true

#spring.mvc.apiversion.use.path-segment=0
#spring.mvc.apiversion.use.query-parameter=version
#spring.mvc.apiversion.use.header=X-API-VERSION
spring.mvc.apiversion.use.media-type-parameter[application/json]=version

Spring Security - Filter Chain
1) All requests should be authenticated
2) If a reqest is not authenticated, a wep page is shown
3) CSRF -> POST, PUT
